@baseUrl = http://localhost:5213
@version = v1

### Create Claim
POST {{baseUrl}}/api/{{version}}/claims
Content-Type: application/json

{
  "coverId": "2F6E1B67-38AE-4347-FE56-08DCE219470B",
  "created": "2024-09-09T10:00:00Z",
  "name": "Explosive Fire Damage",
  "type": 0,
  "damageCost": 10000
}

### Get Claim by Id
GET {{baseUrl}}/api/{{version}}/claims/569A062F-0130-46D6-A22A-08DCE240175E
Content-Type: application/json

### Get all Claims
GET {{baseUrl}}/api/{{version}}/claims
Content-Type: application/json

### DELETE Claim
DELETE {{baseUrl}}/api/{{version}}/claims/CC99E0B8-D2B3-4564-C515-08DCE2432B07
Content-Type: application/json
